-- 创建操作日志表
CREATE TABLE IF NOT EXISTS operation_log (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    request_id VARCHAR(64) NOT NULL COMMENT '请求ID',
    user_id INT COMMENT '用户ID',
    username VARCHAR(100) COMMENT '用户名',
    user_real_name VARCHAR(100) COMMENT '用户真实姓名',
    user_role VARCHAR(50) COMMENT '用户角色',
    ip_address VARCHAR(45) NOT NULL COMMENT 'IP地址',
    user_agent VARCHAR(500) COMMENT '用户代理',
    request_method VARCHAR(10) NOT NULL COMMENT '请求方法',
    request_url VARCHAR(500) NOT NULL COMMENT '请求URL',
    request_params TEXT COMMENT '请求参数',
    response_status INT NOT NULL COMMENT '响应状态码',
    response_time BIGINT NOT NULL COMMENT '响应时间(毫秒)',
    response_result TEXT COMMENT '响应结果摘要',
    operation_type VARCHAR(50) COMMENT '操作类型',
    resource_type VARCHAR(50) COMMENT '资源类型',
    resource_id VARCHAR(50) COMMENT '资源ID',
    operation_desc VARCHAR(200) COMMENT '操作描述',
    module VARCHAR(50) COMMENT '模块',
    is_success BOOLEAN NOT NULL DEFAULT FALSE COMMENT '操作是否成功',
    error_message TEXT COMMENT '错误信息',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',

    INDEX idx_user_id (user_id),
    INDEX idx_username (username),
    INDEX idx_operation_type (operation_type),
    INDEX idx_resource_type (resource_type),
    INDEX idx_module (module),
    INDEX idx_is_success (is_success),
    INDEX idx_ip_address (ip_address),
    INDEX idx_created_at (created_at),
    INDEX idx_request_id (request_id),
    INDEX idx_response_time (response_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='操作日志表';